CompileFlags:
  Add:
    - -std=c++17
    - --cuda-path=/usr/local/cuda
    - --cuda-gpu-arch=sm_75
    - -L/usr/local/cuda/lib64
    - -I/usr/local/cuda/include
    - -ferror-limit=0
    - -O2
    - -Wall
    - -Wextra
    - -Wpedantic
    - -Wno-error=unused-parameter
